services:
  front:
    container_name: front-end
    image: front-end
    hostname: front-end
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - "127.0.0.1:7001:80"
    environment:
      - NODE_ENV=production
